heat_template_version: 2013-05-23

description: |
  Heat template to deploy a load balancer and multiple servers running a PHP app under apache

parameter_groups:

- label: Load Balancer Settings
  parameters:
  - load_balancer_hostname

- label: Server Settings
  parameters:
  - server_hostname
  - image
  - flavor

- label: PHP Application Settings
  parameters:
  - url

parameters:

  load_balancer_hostname:
    label: Load Balancer Hostname
    description: Hostname for the Load Balancer
    type: string
    default: PHP-Load-Balancer
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  server_hostname:
    label: Server Name
    description: Server Name
    type: string
    default: php
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  server_count:
    label: Number Of Servers
    description: Number of servers to deploy
    type: number
    default: 2
    constraints:
    - range:
        min: 0
        max: 24
      description: Must be between 0 and 24 servers.

  image:
    label: Server Image
    description: Server Image
    type: string
    default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      description: Must be a supported operating system.

  flavor:
    label: Server Size
    description: Rackspace Cloud Server flavor
    type: string
    default: 4 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 60 GB Performance
      - 90 GB Performance
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  db_flavor:
    label: Cloud Database Size
    description: Rackspace Cloud Database Flavor
    type: string
    default: 1GB Instance
    constraints:
    - allowed_values:
      - 512MB Instance
      - 1GB Instance
      - 2GB Instance
      - 4GB Instance
      - 8GB Instance
      - 16GB Instance
      description: |
        Must be a valid Rackspace Cloud Database flavor for the region you have
        selected to deploy into.

  db_user:
    label: Database Username
    description: "Username for the database."
    type: string
    default: db_user
    constraints:
    - allowed_pattern: "^(.){1,16}$"
      description: |
        Must be shorter than 16 characters, this is due to MySQL's maximum
        username length.

  db_pass:
    label: Database Password
    description: "Password for the database."
    type: string
    constraints:
    - allowed_pattern: "^(.){8,}$"
      description: Database password must be at least 8 characters long.

  db_size:
    label: Database Size
    type: number
    description: Size of the Rackspace Cloud Database
    default: 10
    constraints:
    - range:
        min: 10
        max: 150
    description: |
        Database instance size, in GB. min 10, max 150

  ssh_keypair_name:
    label: SSH Keypair
    description: Nova keypair name for ssh access to the server
    type: string
    default: php-app

  revision:
    label: Revision
    description: Git Branch/Ref
    type: string
    default: HEAD

  packages:
    label: PHP Packages
    description: PHP Packages
    type: string
    default: ''

  repo:
    label: Git Repo
    description: Git Repo URL
    type: string
    default: ''

  url:
    label: Site Domain
    description: URL for site
    type: string
    default: 'http://example.com'

  deploy_key:
    label: Git Deploy Key
    description: Git deploy key for private repositories.
    type: string
    default: ''

  destination:
    label: Site Path
    description: Deploy Directory
    default: /var/www/vhosts/application
    type: string

  public:
    label: Public Relative Directory
    description: The public facing directory of your application relative to the destination.
    type: string
    default: /

  sslcert:
    description: SSL Certificate
    type: string
    default: false

  sslkey:
    description: SSL Key
    type: string
    default: false

  sslcacert:
    description: SSL CA Certificate
    type: string
    default: false

  # varnish:
  #  description: Install Varnish
  #  type: string
  #  default: false

  http_port:
    label: HTTP Port
    description: HTTP Port
    type: string
    default: 80

  https_port:
    label: HTTPS Port
    description: HTTPS Port
    type: string
    default: 443

  memcached_size:
    label: Memcached Memory Limit
    description: Memcached memory size limit
    type: number
    default: 128

resources:

  database_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 16
      sequence: lettersdigits

  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  php_setup:
    type: "OS::Heat::ResourceGroup"
    properties:
      count: { get_param: server_count }
      resource_def:
        type: https://raw.github.com/rackspace-orchestration-templates/php-app-clouddb/master/php-app-single.yaml
        properties:
          private_key: { get_attr: [ssh_key, private_key] }
          server_hostname: { get_param: server_hostname }
          image: { get_param: image }
          flavor: { get_param: flavor }
          #sslkey: { get_param: sslkey }
          #sslcert: { get_param: sslcert }
          #sslcacert: { get_param: sslcacert }
          revision: { get_param: revision }
          packages: { get_param: packages }
          repo: { get_param: repo }
          url: { get_param: url }
          deploy_key: { get_param: deploy_key }
          destination: { get_param: destination}
          public: { get_param: public }
          # varnish: { get_param: varnish }
          ssh_keypair_name: { get_param: ssh_keypair_name }

  load_balancer:
    type: "Rackspace::Cloud::LoadBalancer"
    depends_on:
    - php_setup
    properties:
      name: { get_param: load_balancer_hostname }
      nodes:
      - addresses: { get_attr: [php_setup, private_ip] }
        port: 80
        condition: ENABLED
      port: 80
      protocol: HTTP
      algorithm: ROUND_ROBIN
      contentCaching: ENABLED
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4

  service_db:
    type: OS::Trove::Instance
    properties:
      name: app_db
      flavor: { get_param: db_flavor }
      size: { get_param: db_size }
      databases:
      - name: app_data
      users:
      - name: { get_param: db_user }
        password: { get_param: db_pass }
        # password: { get_attr: [database_password, value] }
        databases: [ app_data ]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  load_balancer_ip:
    value: { get_attr: [load_balancer, PublicIp]}

  database_id:
    value: { get_resource: service_db }
    description: Database instance ID

  database_hostname:
    value: { get_attr: [service_db, hostname]}
    description: Hostname of the Cloud Database

  # database_password:
  #  value: { get_attr: [database_password, value] }
  #  description: User password for the Cloud Database

  server_public_ips:
    value: { get_attr: [php_setup, public_ip] }
    description: Array of public IP's of the Cloud Servers created

  server_private_ips:
    value: { get_attr: [php_setup, private_ip] }
    description: Array of private IP's of the Cloud Servers created
